services:
  roombarr:
    image: ghcr.io/jacksonblankenship/roombarr:latest
    # build: .
    container_name: roombarr
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
